### ISSUE TITLE
Fatal error on your website.

### ISSUE THREAD

**Issue by magic-space** [nenuadrian/Secret-Republic-Hacking-Browser-Game-V3#10]
Fatal error: Uncaught Error: Class 'Server' not found in /home/dh_mtb3c6/includes/modules/servers/servers.php:47 Stack trace: #0 /home/dh_mtb3c6/secretrepublic-v3.nenuadrian.com/index.php(52): require() #1 {main} thrown in /home/dh_mtb3c6/includes/modules/servers/servers.php on line 47

array (
'errline' => 47,
'errfile' => '/home/dh_mtb3c6/includes/modules/servers/servers.php',
'page' => 'servers/servers',
'url' => 'https://secretrepublic-v3.nenuadrian.com/servers/build/hell/',
'errno' => 1,
'errstr' => 'Uncaught Error: Class 'Server' not found in /home/dh_mtb3c6/includes/modules/servers/servers.php:47
Stack trace:
#0 /home/dh_mtb3c6/secretrepublic-v3.nenuadrian.com/index.php(52): require()
#1 {main}
thrown',
'user_id' => 18151,
'backtrace' => '0',
)

**Comment by nenuadrian** [comment]
Hey magic-space, long time, but if you could try via the newly available setup process and re-submit the bug, I will take a look and let you know

But this looks like you missed changing a reference that causes the code to still look for something relative to my server rather than your local one (since it mensions my local file sistem)
